### ISSUE TITLE
PyPSA Descriptors interface change

### ISSUE THREAD

**Issue by jacquelinedowling** [carnegie/table_pypsa#16]
pypsa.descriptors no longer has a Dict property in version 0.31.0.

Short term we can fix this problem by changing the version in env.yml to pypsa=0.30.3 or some other version <0.31.0.

I believe they moved the Dict to pypsa.definitions.structures in the latest version.

From Eric

**Comment by awongel** [comment]
Thank you, Eric! Resolved in latest PR.
